# Generated by Django 2.0.7 on 2018-08-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmering',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('melding', models.CharField(max_length=200)),
                ('tekstmelding', models.CharField(max_length=200)),
                ('dienstid', models.CharField(max_length=2)),
                ('dienst', models.CharField(max_length=20)),
                ('regioid', models.CharField(max_length=2)),
                ('regio', models.CharField(max_length=200)),
                ('plaats', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('straat', models.CharField(blank=True, max_length=200, null=True)),
                ('datum', models.DateField()),
                ('tijd', models.TimeField()),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lon', models.CharField(blank=True, max_length=20, null=True)),
                ('prio1', models.CharField(max_length=1)),
                ('brandinfo', models.CharField(max_length=50)),
                ('grip', models.CharField(max_length=1)),
                ('capstring', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CapCode',
            fields=[
                ('capcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['capcode'],
            },
        ),
        migrations.AddField(
            model_name='alarmering',
            name='capcodes',
            field=models.ManyToManyField(blank=True, null=True, related_name='alarmeringen', to='alarmeringen.CapCode'),
        ),
        migrations.AddField(
            model_name='alarmering',
            name='subitems',
            field=models.ManyToManyField(blank=True, null=True, related_name='_alarmering_subitems_+', to='alarmeringen.Alarmering'),
        ),
    ]
