# Generated by Django 2.0.7 on 2018-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmering',
            name='brandinfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
