# Generated by Django 2.0.7 on 2018-08-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0003_auto_20180802_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capcode',
            name='omschrijving',
            field=models.CharField(max_length=500),
        ),
    ]
