# Generated by Django 2.0.7 on 2018-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0005_auto_20180803_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmering',
            name='capcodes',
            field=models.ManyToManyField(blank=True, related_name='alarmeringen', to='alarmeringen.CapCode'),
        ),
    ]
