# Generated by Django 2.0.7 on 2018-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0007_auto_20180803_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmering',
            name='capstring',
            field=models.CharField(max_length=1000),
        ),
    ]
