# Generated by Django 2.0.7 on 2018-08-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0009_auto_20180803_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regio',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='alarmering',
            name='regio_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarmeringen', to='alarmeringen.Regio'),
        ),
    ]
