# Generated by Django 2.0.7 on 2018-08-08 08:42
# https://stackoverflow.com/questions/35999186/change-type-of-django-model-field-from-charfield-to-foreignkey

from django.db import migrations


def link_regios(apps, schema_editor):
    Alarmering = apps.get_model('alarmeringen', 'Alarmering')
    Regio = apps.get_model('alarmeringen', 'Regio')
    for alarmering in Alarmering.objects.all():
        regio, created = Regio.objects.update_or_create(
            id=alarmering.regioid,
            defaults={'omschrijving': alarmering.regio})
        alarmering.regio_link = regio
        alarmering.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0010_auto_20180808_1041'),
    ]

    operations = [
        migrations.RunPython(link_regios),
    ]
