# Generated by Django 2.0.7 on 2018-08-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0011_transfer_regio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmering',
            name='regio',
        ),
        migrations.RemoveField(
            model_name='alarmering',
            name='regioid',
        ),
    ]
