# Generated by Django 2.0.7 on 2018-08-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0013_auto_20180808_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='alarmering',
            name='dienst_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarmeringen', to='alarmeringen.Dienst'),
        ),
    ]
