# Generated by Django 2.0.7 on 2018-08-08 18:26
# https://stackoverflow.com/questions/35999186/change-type-of-django-model-field-from-charfield-to-foreignkey

from django.db import migrations


def link_diensten(apps, schema_editor):
    Alarmering = apps.get_model('alarmeringen', 'Alarmering')
    Dienst = apps.get_model('alarmeringen', 'Dienst')
    for alarmering in Alarmering.objects.all():
        dienst, created = Dienst.objects.update_or_create(
            id=alarmering.dienstid,
            defaults={'omschrijving': alarmering.dienst})
        alarmering.dienst_link = dienst
        alarmering.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0014_auto_20180808_2025'),
    ]

    operations = [
        migrations.RunPython(link_diensten),
    ]
