# Generated by Django 2.0.7 on 2018-08-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0015_transfer_dienst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmering',
            name='dienst',
        ),
        migrations.RemoveField(
            model_name='alarmering',
            name='dienstid',
        ),
    ]
