# Generated by Django 2.0.7 on 2018-08-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0016_auto_20180808_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmering',
            old_name='dienst_link',
            new_name='dienst',
        ),
    ]
