# Generated by Django 2.0.7 on 2018-08-13 12:48

from django.db import migrations


def update_plaatsen(apps, schema_editor):
    Alarmering = apps.get_model('alarmeringen', 'Alarmering')
    for alarmering in Alarmering.objects.all():
        if alarmering.postcode is not None:
            alarmering.plaats = alarmering.plaats.replace(alarmering.postcode, '').lstrip()
            alarmering.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alarmeringen', '0017_auto_20180808_2030'),
    ]

    operations = [
        migrations.RunPython(update_plaatsen),
    ]
